insert into planten_soort(id,duur_tot_pluk, max_hoogte, naam_soort) values (1000, 90, 90, 'aardappel')
insert into planten_soort(id,duur_tot_pluk, max_hoogte, naam_soort, oogsttijd) values (2000, 100, 75, 'broccoli', 'juni-oktober')
insert into planten_soort(id,duur_tot_pluk, max_hoogte, naam_soort) values (3000, 42, 90, 'courgette' )
insert into planten_soort(id,duur_tot_pluk, max_hoogte, naam_soort) values (4000, 42, 170 , 'doperwt')
insert into planten_soort(id,duur_tot_pluk, max_hoogte, naam_soort, oogsttijd) values (5000, 10, 10, 'rucola', 'maart-november')
